version: "3"
# Docker Compose to create Reverse proxy & listed services

# Internal network for container use
networks:
  hosting:
    external: false

services: 
  # Gitea instance using SQLITE backend storage
  # to host GIT + front end
  repos:
    image: gitea/gitea:latest
    container_name: repos
    environment:
      - USER_UID=0
      - USER_GID=0
    restart: always
    hostname: repos
    networks:
      - hosting
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3000"
      - "22"

  #Reverse proxy - NGINX
  # To add new services, add appropriate build above for docker container
  # And create a service proxy config file in ./nginx/config/sites
  # Must end in .conf
  ngreverse:
    depends_on:
      - repos
    build: 
      context: ./nginx
      dockerfile: dockerfile
    hostname: ng-proxy
    image: ngproxy:latest
    container_name: ng-reverse-proxy
    networks: 
      - hosting
    ports:
      - "80:80"
      - "443:443"
