# From NGINX, create a reverse proxy
FROM nginx:latest
LABEL maintainer="Michael R Condon <michael.r.condon@gmail.com>"

# Stage config files, including sites list
# Each staged sites/*.conf file will hold a virtual host
RUN ["mkdir", "/etc/nginx/logs"]
COPY ./config/default.conf /etc/nginx/conf.d/default.conf
COPY ./config/sites /etc/nginx/conf.d/sites
# COPY ./config/includes /etc/nginx/includes
# COPY ./config/certs /etc/ssl/certs/nginx




